version: '3'
services:
  phonebook:
    build: .
    container_name: phonebook
    ports:
      - "8081:8080"
    environment:
      OPENSHIFT_MYSQL_DB_HOST: docker-mysql
      OPENSHIFT_MYSQL_DB_PORT: 3306
    depends_on:
      - docker-mysql
    links:
      - docker-mysql
    restart: on-failure
  docker-mysql:
    image: mysql:5.7
    container_name: docker-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notes
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"